version: '3'
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: ./.env
    depends_on:
      - database
    
    networks:
      - rede-producao    


  database:
    image: "postgres"
    healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
            timeout: 45s
            interval: 10s
            retries: 10
    container_name: "database"
    env_file: ./.env
    ports:
      - "5432:5432"

    networks:
      - rede-producao

networks:
  rede-producao:
    driver: bridge

